kind: pipeline
type: docker
name: default

steps:
  - name: hello
    image: busybox
    commands:
      - echo hello everyone good morning

  - name: migration
    image: docker
    volumes:
      - name: docker_sock
        host:
          path: /var/run/docker.sock
        target:
          path: /var/run/docker.sock
    commands:
      - apk update && apk add --no-cache curl
      - curl -sSf https://atlasgo.sh | sh

      - atlas migrate diff all_schema
        --dir "file://ent/migrate/migrations"
        --to "ent://ent/schema"
        --dev-url "docker://postgres/12/test?search_path=public"

      - atlas migrate apply
        --dir "file://ent/migrate/migrations"
        --url "postgres://entgo:mysecretpassword@serveo.net:5432/ent_go_starter?search_path=public&sslmode=disable"
