kind: pipeline
type: docker
name: default

steps:
  - name: hello
    image: busybox
    commands:
      - echo hello everyone good morning

  - name: migrate
    image: busybox
    commands:
      - atlas migrate diff all_schema \
        --dir "file://ent/migrate/migrations" \
        --to "ent://ent/schema" \
        --dev-url "docker://postgres/12/test?search_path=public"

  - name: apply
    image: busybox
    commands:
      - atlas migrate apply \
        --dir "file://ent/migrate/migrations" \
        --url "postgres://entgo:mysecretpassword@localhost:5432/ent_go_starter?search_path=public&sslmode=disable"
