// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"entdemo/ent/commissionstructure"
	"entdemo/ent/predicate"
	"entdemo/ent/userseller"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommissionStructureQuery is the builder for querying CommissionStructure entities.
type CommissionStructureQuery struct {
	config
	ctx                    *QueryContext
	order                  []commissionstructure.Order
	inters                 []Interceptor
	predicates             []predicate.CommissionStructure
	withProductSeller      *UserSellerQuery
	withFKs                bool
	modifiers              []func(*sql.Selector)
	loadTotal              []func(context.Context, []*CommissionStructure) error
	withNamedProductSeller map[string]*UserSellerQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CommissionStructureQuery builder.
func (csq *CommissionStructureQuery) Where(ps ...predicate.CommissionStructure) *CommissionStructureQuery {
	csq.predicates = append(csq.predicates, ps...)
	return csq
}

// Limit the number of records to be returned by this query.
func (csq *CommissionStructureQuery) Limit(limit int) *CommissionStructureQuery {
	csq.ctx.Limit = &limit
	return csq
}

// Offset to start from.
func (csq *CommissionStructureQuery) Offset(offset int) *CommissionStructureQuery {
	csq.ctx.Offset = &offset
	return csq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (csq *CommissionStructureQuery) Unique(unique bool) *CommissionStructureQuery {
	csq.ctx.Unique = &unique
	return csq
}

// Order specifies how the records should be ordered.
func (csq *CommissionStructureQuery) Order(o ...commissionstructure.Order) *CommissionStructureQuery {
	csq.order = append(csq.order, o...)
	return csq
}

// QueryProductSeller chains the current query on the "productSeller" edge.
func (csq *CommissionStructureQuery) QueryProductSeller() *UserSellerQuery {
	query := (&UserSellerClient{config: csq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := csq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := csq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionstructure.Table, commissionstructure.FieldID, selector),
			sqlgraph.To(userseller.Table, userseller.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, commissionstructure.ProductSellerTable, commissionstructure.ProductSellerColumn),
		)
		fromU = sqlgraph.SetNeighbors(csq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CommissionStructure entity from the query.
// Returns a *NotFoundError when no CommissionStructure was found.
func (csq *CommissionStructureQuery) First(ctx context.Context) (*CommissionStructure, error) {
	nodes, err := csq.Limit(1).All(setContextOp(ctx, csq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{commissionstructure.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (csq *CommissionStructureQuery) FirstX(ctx context.Context) *CommissionStructure {
	node, err := csq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CommissionStructure ID from the query.
// Returns a *NotFoundError when no CommissionStructure ID was found.
func (csq *CommissionStructureQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = csq.Limit(1).IDs(setContextOp(ctx, csq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{commissionstructure.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (csq *CommissionStructureQuery) FirstIDX(ctx context.Context) int {
	id, err := csq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CommissionStructure entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CommissionStructure entity is found.
// Returns a *NotFoundError when no CommissionStructure entities are found.
func (csq *CommissionStructureQuery) Only(ctx context.Context) (*CommissionStructure, error) {
	nodes, err := csq.Limit(2).All(setContextOp(ctx, csq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{commissionstructure.Label}
	default:
		return nil, &NotSingularError{commissionstructure.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (csq *CommissionStructureQuery) OnlyX(ctx context.Context) *CommissionStructure {
	node, err := csq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CommissionStructure ID in the query.
// Returns a *NotSingularError when more than one CommissionStructure ID is found.
// Returns a *NotFoundError when no entities are found.
func (csq *CommissionStructureQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = csq.Limit(2).IDs(setContextOp(ctx, csq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{commissionstructure.Label}
	default:
		err = &NotSingularError{commissionstructure.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (csq *CommissionStructureQuery) OnlyIDX(ctx context.Context) int {
	id, err := csq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CommissionStructures.
func (csq *CommissionStructureQuery) All(ctx context.Context) ([]*CommissionStructure, error) {
	ctx = setContextOp(ctx, csq.ctx, "All")
	if err := csq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CommissionStructure, *CommissionStructureQuery]()
	return withInterceptors[[]*CommissionStructure](ctx, csq, qr, csq.inters)
}

// AllX is like All, but panics if an error occurs.
func (csq *CommissionStructureQuery) AllX(ctx context.Context) []*CommissionStructure {
	nodes, err := csq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CommissionStructure IDs.
func (csq *CommissionStructureQuery) IDs(ctx context.Context) (ids []int, err error) {
	if csq.ctx.Unique == nil && csq.path != nil {
		csq.Unique(true)
	}
	ctx = setContextOp(ctx, csq.ctx, "IDs")
	if err = csq.Select(commissionstructure.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (csq *CommissionStructureQuery) IDsX(ctx context.Context) []int {
	ids, err := csq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (csq *CommissionStructureQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, csq.ctx, "Count")
	if err := csq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, csq, querierCount[*CommissionStructureQuery](), csq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (csq *CommissionStructureQuery) CountX(ctx context.Context) int {
	count, err := csq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (csq *CommissionStructureQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, csq.ctx, "Exist")
	switch _, err := csq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (csq *CommissionStructureQuery) ExistX(ctx context.Context) bool {
	exist, err := csq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CommissionStructureQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (csq *CommissionStructureQuery) Clone() *CommissionStructureQuery {
	if csq == nil {
		return nil
	}
	return &CommissionStructureQuery{
		config:            csq.config,
		ctx:               csq.ctx.Clone(),
		order:             append([]commissionstructure.Order{}, csq.order...),
		inters:            append([]Interceptor{}, csq.inters...),
		predicates:        append([]predicate.CommissionStructure{}, csq.predicates...),
		withProductSeller: csq.withProductSeller.Clone(),
		// clone intermediate query.
		sql:  csq.sql.Clone(),
		path: csq.path,
	}
}

// WithProductSeller tells the query-builder to eager-load the nodes that are connected to
// the "productSeller" edge. The optional arguments are used to configure the query builder of the edge.
func (csq *CommissionStructureQuery) WithProductSeller(opts ...func(*UserSellerQuery)) *CommissionStructureQuery {
	query := (&UserSellerClient{config: csq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	csq.withProductSeller = query
	return csq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CommissionStructure.Query().
//		GroupBy(commissionstructure.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (csq *CommissionStructureQuery) GroupBy(field string, fields ...string) *CommissionStructureGroupBy {
	csq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CommissionStructureGroupBy{build: csq}
	grbuild.flds = &csq.ctx.Fields
	grbuild.label = commissionstructure.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.CommissionStructure.Query().
//		Select(commissionstructure.FieldName).
//		Scan(ctx, &v)
func (csq *CommissionStructureQuery) Select(fields ...string) *CommissionStructureSelect {
	csq.ctx.Fields = append(csq.ctx.Fields, fields...)
	sbuild := &CommissionStructureSelect{CommissionStructureQuery: csq}
	sbuild.label = commissionstructure.Label
	sbuild.flds, sbuild.scan = &csq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CommissionStructureSelect configured with the given aggregations.
func (csq *CommissionStructureQuery) Aggregate(fns ...AggregateFunc) *CommissionStructureSelect {
	return csq.Select().Aggregate(fns...)
}

func (csq *CommissionStructureQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range csq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, csq); err != nil {
				return err
			}
		}
	}
	for _, f := range csq.ctx.Fields {
		if !commissionstructure.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if csq.path != nil {
		prev, err := csq.path(ctx)
		if err != nil {
			return err
		}
		csq.sql = prev
	}
	return nil
}

func (csq *CommissionStructureQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CommissionStructure, error) {
	var (
		nodes       = []*CommissionStructure{}
		withFKs     = csq.withFKs
		_spec       = csq.querySpec()
		loadedTypes = [1]bool{
			csq.withProductSeller != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, commissionstructure.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CommissionStructure).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CommissionStructure{config: csq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(csq.modifiers) > 0 {
		_spec.Modifiers = csq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, csq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := csq.withProductSeller; query != nil {
		if err := csq.loadProductSeller(ctx, query, nodes,
			func(n *CommissionStructure) { n.Edges.ProductSeller = []*UserSeller{} },
			func(n *CommissionStructure, e *UserSeller) { n.Edges.ProductSeller = append(n.Edges.ProductSeller, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range csq.withNamedProductSeller {
		if err := csq.loadProductSeller(ctx, query, nodes,
			func(n *CommissionStructure) { n.appendNamedProductSeller(name) },
			func(n *CommissionStructure, e *UserSeller) { n.appendNamedProductSeller(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range csq.loadTotal {
		if err := csq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (csq *CommissionStructureQuery) loadProductSeller(ctx context.Context, query *UserSellerQuery, nodes []*CommissionStructure, init func(*CommissionStructure), assign func(*CommissionStructure, *UserSeller)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CommissionStructure)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.UserSeller(func(s *sql.Selector) {
		s.Where(sql.InValues(commissionstructure.ProductSellerColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.commission_structure_product_seller
		if fk == nil {
			return fmt.Errorf(`foreign-key "commission_structure_product_seller" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "commission_structure_product_seller" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (csq *CommissionStructureQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := csq.querySpec()
	if len(csq.modifiers) > 0 {
		_spec.Modifiers = csq.modifiers
	}
	_spec.Node.Columns = csq.ctx.Fields
	if len(csq.ctx.Fields) > 0 {
		_spec.Unique = csq.ctx.Unique != nil && *csq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, csq.driver, _spec)
}

func (csq *CommissionStructureQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(commissionstructure.Table, commissionstructure.Columns, sqlgraph.NewFieldSpec(commissionstructure.FieldID, field.TypeInt))
	_spec.From = csq.sql
	if unique := csq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if csq.path != nil {
		_spec.Unique = true
	}
	if fields := csq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commissionstructure.FieldID)
		for i := range fields {
			if fields[i] != commissionstructure.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := csq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := csq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := csq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := csq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (csq *CommissionStructureQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(csq.driver.Dialect())
	t1 := builder.Table(commissionstructure.Table)
	columns := csq.ctx.Fields
	if len(columns) == 0 {
		columns = commissionstructure.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if csq.sql != nil {
		selector = csq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if csq.ctx.Unique != nil && *csq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range csq.predicates {
		p(selector)
	}
	for _, p := range csq.order {
		p(selector)
	}
	if offset := csq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := csq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedProductSeller tells the query-builder to eager-load the nodes that are connected to the "productSeller"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (csq *CommissionStructureQuery) WithNamedProductSeller(name string, opts ...func(*UserSellerQuery)) *CommissionStructureQuery {
	query := (&UserSellerClient{config: csq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if csq.withNamedProductSeller == nil {
		csq.withNamedProductSeller = make(map[string]*UserSellerQuery)
	}
	csq.withNamedProductSeller[name] = query
	return csq
}

// CommissionStructureGroupBy is the group-by builder for CommissionStructure entities.
type CommissionStructureGroupBy struct {
	selector
	build *CommissionStructureQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (csgb *CommissionStructureGroupBy) Aggregate(fns ...AggregateFunc) *CommissionStructureGroupBy {
	csgb.fns = append(csgb.fns, fns...)
	return csgb
}

// Scan applies the selector query and scans the result into the given value.
func (csgb *CommissionStructureGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, csgb.build.ctx, "GroupBy")
	if err := csgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommissionStructureQuery, *CommissionStructureGroupBy](ctx, csgb.build, csgb, csgb.build.inters, v)
}

func (csgb *CommissionStructureGroupBy) sqlScan(ctx context.Context, root *CommissionStructureQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(csgb.fns))
	for _, fn := range csgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*csgb.flds)+len(csgb.fns))
		for _, f := range *csgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*csgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := csgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CommissionStructureSelect is the builder for selecting fields of CommissionStructure entities.
type CommissionStructureSelect struct {
	*CommissionStructureQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (css *CommissionStructureSelect) Aggregate(fns ...AggregateFunc) *CommissionStructureSelect {
	css.fns = append(css.fns, fns...)
	return css
}

// Scan applies the selector query and scans the result into the given value.
func (css *CommissionStructureSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, css.ctx, "Select")
	if err := css.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommissionStructureQuery, *CommissionStructureSelect](ctx, css.CommissionStructureQuery, css, css.inters, v)
}

func (css *CommissionStructureSelect) sqlScan(ctx context.Context, root *CommissionStructureQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(css.fns))
	for _, fn := range css.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*css.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := css.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
