// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/contentblock"
	"entdemo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContentBlockDelete is the builder for deleting a ContentBlock entity.
type ContentBlockDelete struct {
	config
	hooks    []Hook
	mutation *ContentBlockMutation
}

// Where appends a list predicates to the ContentBlockDelete builder.
func (cbd *ContentBlockDelete) Where(ps ...predicate.ContentBlock) *ContentBlockDelete {
	cbd.mutation.Where(ps...)
	return cbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cbd *ContentBlockDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ContentBlockMutation](ctx, cbd.sqlExec, cbd.mutation, cbd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cbd *ContentBlockDelete) ExecX(ctx context.Context) int {
	n, err := cbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cbd *ContentBlockDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(contentblock.Table, sqlgraph.NewFieldSpec(contentblock.FieldID, field.TypeInt))
	if ps := cbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cbd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cbd.mutation.done = true
	return affected, err
}

// ContentBlockDeleteOne is the builder for deleting a single ContentBlock entity.
type ContentBlockDeleteOne struct {
	cbd *ContentBlockDelete
}

// Where appends a list predicates to the ContentBlockDelete builder.
func (cbdo *ContentBlockDeleteOne) Where(ps ...predicate.ContentBlock) *ContentBlockDeleteOne {
	cbdo.cbd.mutation.Where(ps...)
	return cbdo
}

// Exec executes the deletion query.
func (cbdo *ContentBlockDeleteOne) Exec(ctx context.Context) error {
	n, err := cbdo.cbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{contentblock.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cbdo *ContentBlockDeleteOne) ExecX(ctx context.Context) {
	if err := cbdo.Exec(ctx); err != nil {
		panic(err)
	}
}
