// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/emailcampaign"
	"entdemo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmailCampaignDelete is the builder for deleting a EmailCampaign entity.
type EmailCampaignDelete struct {
	config
	hooks    []Hook
	mutation *EmailCampaignMutation
}

// Where appends a list predicates to the EmailCampaignDelete builder.
func (ecd *EmailCampaignDelete) Where(ps ...predicate.EmailCampaign) *EmailCampaignDelete {
	ecd.mutation.Where(ps...)
	return ecd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ecd *EmailCampaignDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, EmailCampaignMutation](ctx, ecd.sqlExec, ecd.mutation, ecd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ecd *EmailCampaignDelete) ExecX(ctx context.Context) int {
	n, err := ecd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ecd *EmailCampaignDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(emailcampaign.Table, sqlgraph.NewFieldSpec(emailcampaign.FieldID, field.TypeInt))
	if ps := ecd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ecd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ecd.mutation.done = true
	return affected, err
}

// EmailCampaignDeleteOne is the builder for deleting a single EmailCampaign entity.
type EmailCampaignDeleteOne struct {
	ecd *EmailCampaignDelete
}

// Where appends a list predicates to the EmailCampaignDelete builder.
func (ecdo *EmailCampaignDeleteOne) Where(ps ...predicate.EmailCampaign) *EmailCampaignDeleteOne {
	ecdo.ecd.mutation.Where(ps...)
	return ecdo
}

// Exec executes the deletion query.
func (ecdo *EmailCampaignDeleteOne) Exec(ctx context.Context) error {
	n, err := ecdo.ecd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{emailcampaign.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ecdo *EmailCampaignDeleteOne) ExecX(ctx context.Context) {
	if err := ecdo.Exec(ctx); err != nil {
		panic(err)
	}
}
