// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/predicate"
	"entdemo/ent/primarycontent"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PrimaryContentDelete is the builder for deleting a PrimaryContent entity.
type PrimaryContentDelete struct {
	config
	hooks    []Hook
	mutation *PrimaryContentMutation
}

// Where appends a list predicates to the PrimaryContentDelete builder.
func (pcd *PrimaryContentDelete) Where(ps ...predicate.PrimaryContent) *PrimaryContentDelete {
	pcd.mutation.Where(ps...)
	return pcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pcd *PrimaryContentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, PrimaryContentMutation](ctx, pcd.sqlExec, pcd.mutation, pcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pcd *PrimaryContentDelete) ExecX(ctx context.Context) int {
	n, err := pcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pcd *PrimaryContentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(primarycontent.Table, sqlgraph.NewFieldSpec(primarycontent.FieldID, field.TypeInt))
	if ps := pcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pcd.mutation.done = true
	return affected, err
}

// PrimaryContentDeleteOne is the builder for deleting a single PrimaryContent entity.
type PrimaryContentDeleteOne struct {
	pcd *PrimaryContentDelete
}

// Where appends a list predicates to the PrimaryContentDelete builder.
func (pcdo *PrimaryContentDeleteOne) Where(ps ...predicate.PrimaryContent) *PrimaryContentDeleteOne {
	pcdo.pcd.mutation.Where(ps...)
	return pcdo
}

// Exec executes the deletion query.
func (pcdo *PrimaryContentDeleteOne) Exec(ctx context.Context) error {
	n, err := pcdo.pcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{primarycontent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pcdo *PrimaryContentDeleteOne) ExecX(ctx context.Context) {
	if err := pcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
