// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/predicate"
	"entdemo/ent/productvariation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductVariationDelete is the builder for deleting a ProductVariation entity.
type ProductVariationDelete struct {
	config
	hooks    []Hook
	mutation *ProductVariationMutation
}

// Where appends a list predicates to the ProductVariationDelete builder.
func (pvd *ProductVariationDelete) Where(ps ...predicate.ProductVariation) *ProductVariationDelete {
	pvd.mutation.Where(ps...)
	return pvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pvd *ProductVariationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ProductVariationMutation](ctx, pvd.sqlExec, pvd.mutation, pvd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pvd *ProductVariationDelete) ExecX(ctx context.Context) int {
	n, err := pvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pvd *ProductVariationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(productvariation.Table, sqlgraph.NewFieldSpec(productvariation.FieldID, field.TypeInt))
	if ps := pvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pvd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pvd.mutation.done = true
	return affected, err
}

// ProductVariationDeleteOne is the builder for deleting a single ProductVariation entity.
type ProductVariationDeleteOne struct {
	pvd *ProductVariationDelete
}

// Where appends a list predicates to the ProductVariationDelete builder.
func (pvdo *ProductVariationDeleteOne) Where(ps ...predicate.ProductVariation) *ProductVariationDeleteOne {
	pvdo.pvd.mutation.Where(ps...)
	return pvdo
}

// Exec executes the deletion query.
func (pvdo *ProductVariationDeleteOne) Exec(ctx context.Context) error {
	n, err := pvdo.pvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productvariation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pvdo *ProductVariationDeleteOne) ExecX(ctx context.Context) {
	if err := pvdo.Exec(ctx); err != nil {
		panic(err)
	}
}
