// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/productattribute"
	"entdemo/ent/productvariation"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductVariationCreate is the builder for creating a ProductVariation entity.
type ProductVariationCreate struct {
	config
	mutation *ProductVariationMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pvc *ProductVariationCreate) SetName(s string) *ProductVariationCreate {
	pvc.mutation.SetName(s)
	return pvc
}

// SetDescription sets the "description" field.
func (pvc *ProductVariationCreate) SetDescription(s string) *ProductVariationCreate {
	pvc.mutation.SetDescription(s)
	return pvc
}

// SetPrice sets the "price" field.
func (pvc *ProductVariationCreate) SetPrice(s string) *ProductVariationCreate {
	pvc.mutation.SetPrice(s)
	return pvc
}

// AddProductAttributeIDs adds the "productAttributes" edge to the ProductAttribute entity by IDs.
func (pvc *ProductVariationCreate) AddProductAttributeIDs(ids ...int) *ProductVariationCreate {
	pvc.mutation.AddProductAttributeIDs(ids...)
	return pvc
}

// AddProductAttributes adds the "productAttributes" edges to the ProductAttribute entity.
func (pvc *ProductVariationCreate) AddProductAttributes(p ...*ProductAttribute) *ProductVariationCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pvc.AddProductAttributeIDs(ids...)
}

// Mutation returns the ProductVariationMutation object of the builder.
func (pvc *ProductVariationCreate) Mutation() *ProductVariationMutation {
	return pvc.mutation
}

// Save creates the ProductVariation in the database.
func (pvc *ProductVariationCreate) Save(ctx context.Context) (*ProductVariation, error) {
	return withHooks[*ProductVariation, ProductVariationMutation](ctx, pvc.sqlSave, pvc.mutation, pvc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pvc *ProductVariationCreate) SaveX(ctx context.Context) *ProductVariation {
	v, err := pvc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pvc *ProductVariationCreate) Exec(ctx context.Context) error {
	_, err := pvc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pvc *ProductVariationCreate) ExecX(ctx context.Context) {
	if err := pvc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pvc *ProductVariationCreate) check() error {
	if _, ok := pvc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProductVariation.name"`)}
	}
	if _, ok := pvc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ProductVariation.description"`)}
	}
	if _, ok := pvc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "ProductVariation.price"`)}
	}
	return nil
}

func (pvc *ProductVariationCreate) sqlSave(ctx context.Context) (*ProductVariation, error) {
	if err := pvc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pvc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pvc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pvc.mutation.id = &_node.ID
	pvc.mutation.done = true
	return _node, nil
}

func (pvc *ProductVariationCreate) createSpec() (*ProductVariation, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductVariation{config: pvc.config}
		_spec = sqlgraph.NewCreateSpec(productvariation.Table, sqlgraph.NewFieldSpec(productvariation.FieldID, field.TypeInt))
	)
	if value, ok := pvc.mutation.Name(); ok {
		_spec.SetField(productvariation.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pvc.mutation.Description(); ok {
		_spec.SetField(productvariation.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := pvc.mutation.Price(); ok {
		_spec.SetField(productvariation.FieldPrice, field.TypeString, value)
		_node.Price = value
	}
	if nodes := pvc.mutation.ProductAttributesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productvariation.ProductAttributesTable,
			Columns: []string{productvariation.ProductAttributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productattribute.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProductVariationCreateBulk is the builder for creating many ProductVariation entities in bulk.
type ProductVariationCreateBulk struct {
	config
	builders []*ProductVariationCreate
}

// Save creates the ProductVariation entities in the database.
func (pvcb *ProductVariationCreateBulk) Save(ctx context.Context) ([]*ProductVariation, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pvcb.builders))
	nodes := make([]*ProductVariation, len(pvcb.builders))
	mutators := make([]Mutator, len(pvcb.builders))
	for i := range pvcb.builders {
		func(i int, root context.Context) {
			builder := pvcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductVariationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pvcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pvcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pvcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pvcb *ProductVariationCreateBulk) SaveX(ctx context.Context) []*ProductVariation {
	v, err := pvcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pvcb *ProductVariationCreateBulk) Exec(ctx context.Context) error {
	_, err := pvcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pvcb *ProductVariationCreateBulk) ExecX(ctx context.Context) {
	if err := pvcb.Exec(ctx); err != nil {
		panic(err)
	}
}
