// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/predicate"
	"entdemo/ent/userinfluencer"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserInfluencerDelete is the builder for deleting a UserInfluencer entity.
type UserInfluencerDelete struct {
	config
	hooks    []Hook
	mutation *UserInfluencerMutation
}

// Where appends a list predicates to the UserInfluencerDelete builder.
func (uid *UserInfluencerDelete) Where(ps ...predicate.UserInfluencer) *UserInfluencerDelete {
	uid.mutation.Where(ps...)
	return uid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uid *UserInfluencerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, UserInfluencerMutation](ctx, uid.sqlExec, uid.mutation, uid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uid *UserInfluencerDelete) ExecX(ctx context.Context) int {
	n, err := uid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uid *UserInfluencerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userinfluencer.Table, sqlgraph.NewFieldSpec(userinfluencer.FieldID, field.TypeInt))
	if ps := uid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uid.mutation.done = true
	return affected, err
}

// UserInfluencerDeleteOne is the builder for deleting a single UserInfluencer entity.
type UserInfluencerDeleteOne struct {
	uid *UserInfluencerDelete
}

// Where appends a list predicates to the UserInfluencerDelete builder.
func (uido *UserInfluencerDeleteOne) Where(ps ...predicate.UserInfluencer) *UserInfluencerDeleteOne {
	uido.uid.mutation.Where(ps...)
	return uido
}

// Exec executes the deletion query.
func (uido *UserInfluencerDeleteOne) Exec(ctx context.Context) error {
	n, err := uido.uid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userinfluencer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uido *UserInfluencerDeleteOne) ExecX(ctx context.Context) {
	if err := uido.Exec(ctx); err != nil {
		panic(err)
	}
}
